---
name: Last Release Weekly Tests

on:
  schedule:
    - cron: '0 0 * * 0'  # At 00:00 on Sunday
  workflow_dispatch:

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1
        with:
          skip-creation: true

      - name: Run s3gw's tests
        env:
          SKIP_IMPORT_IMAGES: 1
          CHARTS_VER_PREV: "0.16.0"
          CHARTS_VER: "0.17.0"
          IMAGE_TAG_PREV: "0.16.0"
          IMAGE_TAG: "0.17.0"
        run: |
          make acceptance-cluster-create
          make acceptance-cluster-prepare
          make acceptance-test-install
          make acceptance-test-upgrade
          make acceptance-test-cosi
