---
name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Every night midnight
  workflow_dispatch:

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout Ceph HEAD
        working-directory: ceph
        run: |
          git fetch
          git checkout s3gw
          git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Setup k3d
        uses: nolar/setup-k3d-k3s@v1
        with:
          skip-creation: true

      - name: Build s3gw's images and run tests
        run: |
          make acceptance-cluster-create
          make build-images
          make acceptance-cluster-prepare
          make acceptance-test-install
